include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_relative_imports: true
    directives_ordering: true
analyzer:
  errors:
    prefer_relative_imports: error
    directives_ordering: error






